language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t matzexcom/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true matzexcom/docker-react npm run test -- --coverage